---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: swethareddy1999/minnu:dockerwebapp
   ports:
     - "3306:3306"

 application:
   image: swethareddy1999/minnu:dockerwebdb
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
